### ISSUE TITLE
Generic Constructors

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight-Labs/metadsl#69]
# `metadsl` design question

In my current work to [support conversions](https://github.com/Quansight-Labs/metadsl/pull/62) I am wrestling with the question: "How should generic constructors be handled? With class methods or with functions"?

Let's look at a concrete example. We have a `List` class that defines a getitem method:

```python
import typing
import metadsl


class List(metadsl.Expression, typing.Generic[T]):
    @expression
    def __getitem__(self, i: int) -> T:
        ...
```

Now, we would like to create an instance of this list class from a number of Python items. One way would be to have a function:

```python
@expression
def create_list(item_typing: typing.Type[T], *items: T) -> List[T]:
    ...

l  = create_list(str, "hi", "there")
```

Why do we need to add the type as the first parameter? Well if we are creating an empty list, we can't infer it from the items inside it.

We could also create this as a class method:

```python
class List(metadsl.Expression, typing.Generic[T]):
    @expression
    def __getitem__(self, i: int) -> T:
        ...

    @expression
    @classmethod
    def create(*items: T) -> List[T]:
        ...

l = List[str].create("hi", "there")
```

Here we also specify the type, but we can do it as a parameter to the class. This feels a bit more "pythonic" since this is the established
syntax for generic classes.

However, it isn't extensible, meaning that if I define the `List` class in one library, and someone wants to write a new constructor for it,
they have to modify my code. The function syntax is extensible, in that anyone can write a constructor for any type.

Unfortunately there is no syntax like `create_list[str]("hi", "there")`.  At the typing summit at runtime, this was brought up, but there wasn't much support for it and it was shot down because it would mean calling getitem on functions wouldn't result in a runtime exception, which might be confusing. We could support this at runtime, of course, but it is not compatible with MyPy. Currently, I don't believe there is any way to write a decorator that takes in a callable and returns something like this. But maybe
that would be a good way to do it, with a `MyPy` plugin that allows this form for our decorated functions.

In the meantime, we could just pass in the type manually as a first argument.

---

The other question is how we would store this in the graph. For the classmethod approach, we actually have a couple of options. Normally in Python, if you access a classmethod you get a bound function that also holds onto the original class. So we could store this in the graph, so it would look like:

```python
List(function=List[str].create, arguments=("hi", "there"))
```

Or, we could store the original function in the graph and add the class to the args:

```python
List(function=List.create, arguments=(List[str], "hi", "there"))
```

The advantage of the second approach is that we might actually be doing pattern matching at the type level. Right now, our pattern matching
just treats functions as exact matches when pattern matching. With this approach, we would have to traverse the types of the functions to extract out their types.

---

But I think I have convinced myself that the function approach is probably most straightforward. It isn't the most ergonomic, but we could improve that with a MyPy plugin. It also has the advantage of not having to mess with descriptors. I actually [have this working](https://github.com/python/typing/issues/629#issuecomment-493683034) at the moment,
but it's pretty complicated to write a decorator like `expression` that will properly create the Expression based on the class arguments. And
it requires monkeypatching typing to allow extracting the `str` from `List[str]`.

I would appreciate any other perspectives on this or the broader context. I am sure there are many things I am missing here.

**Comment by saulshanabrook** [comment]
Two other points I forgot:

The actual class of the returned expression should be generic, so it should really look like this:

```python
List[str](function=List[str].create, arguments=("hi", "there"))
# or 
List[str](function=List.create, arguments=(List[str], "hi", "there"))
# or 
List[str](function=create_list, arguments=(str, "hi", "there"))
```

The other point is that I want to maintain that:

> If `e` is an expression than `e.function(*e.arguments) == e`. 

Given these rules, it looks li,e for the second one to work, the `function` would have to be the originally defined `create` function, not the function returned by `List.create`. Because the function returned there is a bound method. This option also creates some oddness in that for non generic classes the first argument is redundant, obviously the class is the first argument passed in. Assuming no inheritance (which we don't allow currently), then there could be no other value there.

So this brings us to the third option as possibly the most consistent. There is only one version of the function itself, and calling it with its arguments will return itself in an obvious way.

Like I mentioned above, the functional approach is also more extensible, so anyone can add a constructor function without having to add a method to the class. It comes at the cost of some clarity for usage (`create_list(str, "hi")` is less pythonic than `List[str].create("hi")` I believe), but this will only be used internally anyway, users will not be exposed to these functions unless they are writing an extension library.

So the tentative conclusion **go with the function approach and not support class methods**.

---

## Implications

This has implications for creating expressions and for creating replacements.

Let's use this as an example, since it doesn't have variable args, which simplifies things a bit:

```python
import typing
import metadsl


T = typing.TypeVar("T") 
U = typing.TypeVar("U")

class Abstraction(metadsl.Expression, typing.Generic[T, U]):
    @metadsl.expression
    def __call__(self, arg: T): U:
        ...


class Optional(metadsl.Expression, typing.Generic[T]):
    @metadsl.expression
    def match(none: U, some: Abstraction[T, U]):
        ...


@expression
def none(type: typing.Type[T]): Optional[T]:
    ...

@expression
def some(value: T): Optional[T]:
    ...
```

Here we first define an `Abstraction` which is a lambda calculus term for just a function with one argument, which is easier to type in Python than a variable lengths function, because we don't have variable generics.

Anyway, what we wanna be able to do here is create optional types of either a value or of nothing, and then replace those with one expression if its nothing, or another if its something. So we want our behavior to be:

```python

def create_abstraction(fn: typing.Callable[[T], U]) -> Abstraction[T, U]:
    # Pretend we have this defined, we can do this as a lambda term
    # but I won't go through this here
    ... 

class Integer(metadsl.Expression):
     @expression
     def double(self): Integer:
        ...

@expression
def integer(i: int): Integer:
    ...


an_int = some(integer(3))
no_int = none(Integer)

def process_optional_int(i: Optional[Integer]) -> Integer:
    """
    Return 10 if no integer passed in, otherwise return double integer 
    """
    return i.match(integer(10), create_abstraction(lambda i: i.double()))


assert replace_optional(process_optional_int(an_int)) == integer(3).double()
assert replace_optional(process_optional_int(no_int)) == integer(10)
```

So we can write our `replace_optional` rule like this:


```python
@metadsl.rule
def replace_optional_none(t: typing.Type[T], n: U, s: Abstraction[T, U]) -> metadsl.R[U]:
    return none(t).match(n, s), n

@metadsl.rule
def replace_optional_some(v: T, n: U, s: Abstraction[T, U]) -> metadsl.R[U]:
    return some(v).match(n, s), s(v)


replace_optional = metadsl.combine_rules(replace_optional_none, replace_optional_some)
```
**So not only does the rule system have to support injecting generic types, like `T` into the rules as wildcards, it also should support injecting things like `typing.Type[T]`.**

**Comment by saulshanabrook** [comment]
I have made my way enough through this implementation to see where it gets.... odd. Let's look at an example with the conversion system and the optional type. We want to say that if you are trying to convert something to an optional type, and the value is a `None`, then we should instantiate an optional type with `none`:

```python
@expression
def convert(type: typing.Type[T], value: object) -> T:
    """
    Converts a value to a certain type.
    """
    ...

class Optional(Expression, typing.Generic[T]):
    pass


@expression
def some(value: T) -> Optional[T]:
    ...


@expression
def none(tp: typing.Type[T]) -> Optional[T]:
    ...
```

Now let's try to write this rule:

```python
@rule
def convert_optional_none() -> R[Optional[T]]:
    return convert(Optional[T], None), lambda: none(T)
```

This is already a bit wonky because we are using `T` basically as a wildcard type that should be replaced with the value. Fine, weird, but I guess makes some sense. The issue though is that MyPy complains at `none(T)`: `'T' is a type variable and only valid in type context`.

Well let's try passing in the generic type as a parameter, like this:

```python
@rule
def convert_optional_none(tp: typing.Type) -> R[Optional]:
    """
    When the value is an instance of the type being converted, we can convert it.
    """
    return convert(Optional[tp], None), lambda: none(tp)
```

Well now MyPy complains on the other end, about `Optional[tp]`: `Invalid type "tp"`.

So to satisfy MyPy, either the type arg for `Optional` becomes part of its constructor  or we could try to allow passing in the type to none as a class parameter, instead of a function. This would require introducing classmethods again:

```python
class Convert(Expression, typing.Generic[T]):
    @expression
    @classmethod
    def convert(cls, value: object) -> T:
        ...


class Optional(Expression, typing.Generic[T]):
    @expression
    @classmethod
    def some(cls, value: T) -> Optional[T]:
        ...

    @expression
    @classmethod
    def none(cls) -> Optional[T]:
        ...


@rule
def convert_optional_none() -> R[Optional[T]]:
    """
    When the value is an instance of the type being converted, we can convert it.
    """
    return Convert[Optional[T]].convert(None), lambda: Optional[T].none()
```

Now MyPy is happy because all type variables are on the generic.

So this seems to suggest going back to the class method based approach. I guess with something maybe like this?

```python
Optional[int].none() == Optional[int](Optional[int].none, (), {})
Optional[int].some(123) == Optional[int](Optional[int].some, (123,), {})
```

Or we add some `# type: ignore` lines and move on.

---

It is a worrying issue, because this choice informs how a lot of the other APIs are written and how the core type analysis code handles things. And I am unsure who to ask for guidance on a best practice here. This is probably due to the hesitance of the typing team to support any runtime usage, but on the other side I would like to provide a pleasant API for users and reusing type annotations simplifies things for them.

**Comment by saulshanabrook** [comment]
I opened https://github.com/python/mypy/issues/6964 to see if we could get MyPy to stop raising an error on the first example, so that we could write this:

```python
@rule
def convert_optional_none() -> R[Optional[T]]:
    return convert(Optional[T], None), lambda: none(T)
```

**Comment by scopatz** [comment]
Hi @saulshanabrook - I think some of this is you being contrained by the current limitations in MyPy. 

Personally, the classmethod based approach seems like it is the most natural and flexible (maybe that is my years of C++ talking though). Perhaps the function based approach is just more "functional." The following is really a nice and concise representation.

```
@rule
def convert_optional_none() -> R[Optional[T]]:
    return convert(Optional[T], None), lambda: none(T)
```

 Let's see what they say about python/mypy#6964 as that seems like the right way to go at first glance

**Comment by saulshanabrook** [comment]
> Personally, the classmethod based approach seems like it is the most natural and flexible (maybe that is my years of C++ talking though.

Yeah, I am leaning towards this now as well, since it keeps all type like things in the class getitem syntax, which is what MyPy encourages.

I also am not hopeful that the MyPy team will go for that issue, given the lack of support for runtime usage of typing machinery.

So yeah, we may be forced into the classmethod approach (which is actually not supported at runtime, but we can get around that more easily than messing with MyPy https://github.com/python/typing/issues/629)

**Comment by hameerabbasi** [comment]
I'd really prefer it if we had the class approach with `__init__` being the user-facing method and `.create` being the dev-facing method.

**Comment by saulshanabrook** [comment]
On the call today we were pretty split on which one we all preferred. @costrouc liked the functional approach more, but thought the class based one was more pythonic. @rgommers liked the functional approach more. Chris suggested maybe we support both.

---

Here is another complete example of both approaches, with the use case of converting to an optional type.



## Functional

```python
class Optional(Expression, typing.Generic[T]):
    pass

@expression
def some(value: T) -> Optional[T]:
    ...


@expression
def none(tp: typing.Type[T]) -> Optional[T]:
    ...


@expression
def convert(type: typing.Type[T], value: object) -> Optional[T]:
    """
    Converts a value to a certain type or none if it cannot.
    """
    ...


@rule
def convert_optional(x: object) -> R[Optional[Optional[T]]]:
    return (
        convert(Optional[T], x),
        lambda: some(none(T) if x is None else convert(T, x)),
    )


assert convert_optional(convert(Optional[int], None)) == some(none(int))
assert convert_optional(convert(Optional[int], 123)) == some(some(convert(int, 123)))
```

## Classes

```python
class Optional(Expression, typing.Generic[T]):
    @classmethod
    @expression
    def some(cls, value: T) -> Optional[T]:
        ...

    @classmethod
    @expression
    def none(cls) -> Optional[T]:
        ...


class Converter(Expression, typing.Generic[T]):
    @classmethod
    @expression
    def convert(cls, value: object) -> Optional[T]:
        """
        Converts a value to type T or none if it cannot.
        """
        ...


@rule
def convert_optional(x: object) -> R[Optional[Optional[T]]]:
    return (
        Converter[Optional[T]].convert(x),
        lambda: Optional.some(
            Optional[T].none() if x is None else Converter[T].convert(x)
        ),
    )


assert convert_optional(Converter[int].convert(None)) == Optional.some(
    Optional[int].none()
)
assert convert_optional(Converter[int].convert(123)) == Optional.some(
    Converter[int].convert(123)
)
```

**Comment by saulshanabrook** [comment]
I am moving forward on the class based constructors, since they work better with MyPy and more cleanly separate type parameters from other parameters. Progress is being made in https://github.com/Quansight-Labs/metadsl/pull/62
